### ISSUE TITLE
Consider adding older python compatability

### ISSUE THREAD

**Issue by Crypt0-Bear** [EgosOwn/monerosms-client#2]
MoneroSMS requires Python 3.10+

Taking a look at the source the only thing I saw requiring this was the match/switch statements. 
Consider changing it to a switch or if  elif statements to make it easier for older versions of python. 

There are a lot of different linux distros who don't make it very easy to use the latest python versions out of the box. Many people just add an alternate ppa but this adds another layer of trust. Building from source takes some time. 

Might help expand potential user base.

**Comment by EgosOwn** [comment]
Yeah, i'll switch it to if eventually - it is problematic for Debian users.

**Comment by EgosOwn** [comment]
I plan to rewrite this in Go #5
