### ISSUE TITLE
Error 401 gets returned when trying to send message with monerosms.py (script needs to correctly reformat numbers)

### ISSUE THREAD

**Issue by xWolpertinger01** [EgosOwn/monerosms-client#4]
Whenever I try to send a message with
`python3 monerosms.py send "(+1.../insert random US-number here)"`
I get a _error 401_ returned.

I did not configure my _appconfig.py_ or _send.py_ as I don't want to mess with the files but I did configure my _monerosms-auth_.

Please help me with this

![screenshot-from_10⁄18⁄24_at_02;29](https://github.com/user-attachments/assets/f94a70c6-50dd-416e-a0fe-3e42844e3e76)

**Comment by EgosOwn** [comment]
Thank you for your report, I appreciate the time you took to make it.

This is a result of poor number format handling in the script. I will release a fixed version but for now you should be able to work around it by not putting +1 (just put the 9 digits)
